### ISSUE TITLE
Delete on Server fails

### ISSUE THREAD

**Issue by realholgi** [squix78/espaper-client#11]
If I press the delete Button on a device, I see a message "Internal Server Error" and the device is not deleted.

![shot](https://user-images.githubusercontent.com/980419/34821213-41dddf6c-f6c3-11e7-8f3c-a474e600e04d.png)

**Comment by realholgi** [comment]
same for applications

**Comment by squix78** [comment]
Deleting devices should now work. Cause for the problem was referential integrity: with each request from the device a log entry is created which has a reference to devices. Now deleting the device will cascade also to the log. Introducing cascading delete for applications would also delete the device and I don't think this would be expected behavior. We probably should show a message saying that there is a device using this application and thus the application cannot be deleted. What do you think? And can you confirm that deleting the device now works?

**Comment by realholgi** [comment]
No sorry, still "Internal Server Error" on deleting Device 12 and Application 18. Order of deletion does not matter.

**Comment by realholgi** [comment]
I can delete an application, it it is not used in any device.

But now I have a device left, I cannot delete even with no application selected...

**Comment by squix78** [comment]
Can you please try again? The new database constraint was not applied properly before.

**Comment by realholgi** [comment]
Yay! works now!
